/**
 * Compiles the Tailwind classes of every theme marked `tailwind: true` into themes/generated/tailwind.ts,
 * which the renderer inlines. Runs before the type check (`npm run build`); run it by hand after editing a
 * Tailwind theme: npm run themes:tailwind
 * Utilities map to the page tokens (bg-accent, text-ink, font-display…), so each business keeps its palette.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const themesDir = resolve(import.meta.dirname, '../themes');
const cli = resolve(import.meta.dirname, '../../../node_modules/.bin/tailwindcss');
const out = join(themesDir, 'generated/tailwind.ts');

// Read the flag from the source, so this runs before the themes (which import the generated file) compile.
const ids = readdirSync(themesDir)
  .filter((file) => file.endsWith('.ts') && file !== 'index.ts')
  .filter((file) => /^\s*tailwind:\s*true\b/m.test(readFileSync(join(themesDir, file), 'utf8')))
  .map((file) => file.replace(/\.ts$/, ''));

// Inside the package (out/ is git-ignored), so Tailwind resolves its own CSS from node_modules.
const tmp = resolve(import.meta.dirname, '../out/.tailwind');
mkdirSync(tmp, { recursive: true });
const css: Record<string, string> = {};
try {
  for (const id of ids) {
    const input = join(tmp, `${id}.css`);
    writeFileSync(
      input,
      `@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css" layer(utilities) source(none);
@source "${join(themesDir, `${id}.ts`)}";
@theme inline {
  --color-ink: var(--ink);
  --color-paper: var(--paper);
  --color-accent: var(--accent);
  --color-on-accent: var(--on-accent);
  --font-display: var(--font-display);
  --font-body: var(--font-body);
}
`,
    );
    const output = join(tmp, `${id}.out.css`);
    execFileSync(cli, ['-i', input, '-o', output, '--minify'], { stdio: 'pipe', cwd: resolve(import.meta.dirname, '..') });
    const compiled = readFileSync(output, 'utf8');
    // Embedded in <style>: nothing may close it. (Tailwind itself writes `syntax:"<color>"`, which is fine.)
    if (/<\/style/i.test(compiled)) throw new Error(`${id}: compiled CSS contains "</style"`);
    css[id] = compiled;
  }
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

writeFileSync(
  out,
  `// Generated by scripts/build-tailwind.ts (npm run themes:tailwind). Do not edit.
export const TAILWIND_CSS: Record<string, string> = ${JSON.stringify(css, null, 2)};
`,
);
console.log(`Tailwind: ${ids.length ? ids.map((id) => `${id} (${(css[id]!.length / 1024).toFixed(1)} KB)`).join(', ') : 'no themes use it'} → ${out}`);
